# Generated by Django 4.2.6 on 2023-11-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
