# Generated by Django 4.2.6 on 2023-11-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_remove_user_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
