# Generated by Django 4.2.6 on 2023-11-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_alter_profile_profileimg_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
