# Generated by Django 4.2.6 on 2023-11-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0012_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
