# Generated by Django 4.2.9 on 2024-02-09 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0017_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_messages', to='recipeapp.recipe'),
        ),
    ]
