# Generated by Django 4.2.4 on 2024-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0019_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calorie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
